version: '3.8'
services:
  backend:
    build: ./backend
    env_file: ./backend/.env.example
    ports:
      - "8000:8000"
  frontend:
    build: ./frontend
    environment:
      - VITE_API_BASE_URL=http://localhost:8000
    ports:
      - "3000:3000"
    depends_on:
      - backend
